//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaratApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Advertisement
    {
        public int AdverId { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public byte[] Photo { get; set; }
        public int Type { get; set; }
        [JsonIgnore]
        public virtual TypesAdvertisiment TypesAdvertisiment { get; set; }
    }
}
